GET http://localhost:2112/api/users

###
GET http://localhost:2112/api/users/4

###
POST http://localhost:2112/api/users
Content-Type: application/json

{
    "name": "naming"
}

###
PUT http://localhost:2112/api/users/1
Content-Type: application/json

{
    "id": 22,
    "name": "mantle"
}

###
DELETE http://localhost:2112/api/users/12